name: CI Pipeline

# Ejecutar en push y pull requests a main
on:
  push:
    branches: [ main]
 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ejecutar tests con pytest
      run: |
        pytest test_calculadora.py -v
